console.log('javascript with external link')
console.log(typeof 'sanghpal')
console.log(typeof 10)
console.log(typeof true)
console.log(typeof null)
console.log(typeof undefined)
//this is single line comment
/*this is multiple line comment*/
let firstname='sanghpal'
let lastname='kamble'
let age=19
let isMarried=false
console.log(firstname,lastname,age,isMarried)
/*Data types can be divided into two.
1.primitive datatype
2.non-primitive datatype


-1.primitive datatypes
   
   .Numbers-integers,floats
   .strings-any datatype under single qoute,double qoute or backtick qoute
   .Booleans-true or false value
   .NUll-empty valueor no value
   .undefined-a declare variable without a value
   .symbol- a unique symbol which can be generated by symbol constuctor
   
-2.non-primitive datatypes
    
   .objects
   .arrays
   */

let nums=[1,2,3]
 nums[0]=10
 console.log(nums)


 let num1=[1,2,3]
 let num2=[1,2,3]
 console.log(num1==num2)


 let userone={
    name:'sanghpal',
    role:'leader',
    country:'india',
    age:19
}                   //false
let usertwo={
    name:'sanghpal',
    role:'leader',
    country:'india',
    age:19
}                  //false
console.log(userone==usertwo)


let numb=[1,2,3]
let numbe=numb    //true
console.log(numb==numbe)

let user={
    name:'sanghpal',
    role:'leader',
    country:'india',
    age:19
}                //true
let user1=user
console.log(user==user1)


//----NUMBERS----//

let age1=35
const gravity= 9.81 //we use const for non changing values
let mass= 72        //mass in kilogram
const pi=3.14       //pi is a gemotrical constant
console.log(age1,gravity,mass,pi)

//----MATH OBJECT----//

const pi1=Math.PI
console.log(pi1)
console.log(Math.round(pi1))//3 to round values to the nearest number
console.log(Math.round(9.81))//10 to round value to the nearest number
console.log(Math.floor(pi1))//3 rounding up
console.log(Math.ceil(pi1))//4 rounding up
console.log(Math.min(-3,1,16,4,8,9,0))//returns lowest value -3
console.log(Math.max(-3,1,16,4,8,9,0))//returns highest value 16

const randnum=Math.random()//creates random number from 0to0.99999
console.log(randnum)
const randnum1=Math.floor(Math.random()*11)//creates random number from 0to10
console.log(randnum1)

console.log(Math.abs(-20)) //20 absolute value

console.log(Math.sqrt(100))  //10 square root

console.log(Math.pow(3,2))  //9

console.log(Math.E)

//Logrithm
// retuerns the natural logrithm with base E of x,Math.log(x)
console.log(Math.log(2))

console.log(Math.log(10))

//returns the naturral logrtithm of 2 and 10 respectively
console.log(Math.LN2)
console.log (Math.LN10)

//trignometry
console.log(Math.sin(3))
console.log(Math.cos(3))

let randnumb=Math.random()
let numBtnZeroAndTen=randnumb *20
console.log(numBtnZeroAndTen)

let RandomNumRoundToFloor=Math.floor(numBtnZeroAndTen)
console.log(RandomNumRoundToFloor)